spring.application.name=articulos
spring.datasource.url=jdbc:mysql://localhost:3306/articulos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Nota, se le quitó al 8 a MySQL8Dialect porque no funcionaba.
# Según esta recomendación de un foro: https://stackoverflow.com/questions/25481330/how-to-resolve-dialect-class-not-found-org-hibernate-dialect-mysqldialect-exc
# Original:
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
